### PR TITLE
Benchmark dot operator 

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
Setup: `p2.8xlarge`, compiled with 
```
USE_OPENMP=1, DEV=0, DEBUG=0, USE_MKL2017=0, USE_MKL2017_EXPERIMENTAL=0, USE_BLAS=openblas
```

```
ubuntu@ip-172-31-33-77:~ $ python ./benchmark/python/sparse_op.py
A = sparse NDArray of shape(m, k)
B = dense NDArray of shape(k, n)

dot_forward     dot(csr, dns)
density(%)      context n       m       k       t_sparse        t_dense t_sparse/t_dense
5.0             cpu(0)  50      512     50000   0.107473        0.07950 1.35
2.0             cpu(0)  50      512     50000   0.037989        0.04614 0.82
1.0             cpu(0)  50      512     50000   0.019648        0.04613 0.43
0.5             cpu(0)  50      512     50000   0.010569        0.04618 0.23
0.1             cpu(0)  50      512     50000   0.002689        0.04633 0.06

5.0             cpu(0)  100     512     100000  0.706307        0.07776 9.08
2.0             cpu(0)  100     512     100000  0.175632        0.07767 2.26
1.0             cpu(0)  100     512     100000  0.081770        0.07748 1.06
0.5             cpu(0)  100     512     100000  0.044006        0.07770 0.57
0.1             cpu(0)  100     512     100000  0.010350        0.07731 0.13

dot_backward    dot(csr.T, dns)
density(%)      context n       m       k       t_sparse        t_dense t_sparse/t_dense
5.0             cpu(0)  50      512     50000   89.038583       0.05922 1503.65
2.0             cpu(0)  50      512     50000   74.109367       0.05911 1253.69
1.0             cpu(0)  50      512     50000   71.950517       0.05902 1219.13
0.5             cpu(0)  50      512     50000   55.482324       0.05920 937.19
0.1             cpu(0)  50      512     50000   24.582513       0.05941 413.74
```

@reminisce the time reported for dot(csr.T, dns) report by the script is very slow. Did you notice this before?

### CODE REVIEW

**Comment by reminisce** [comment]
The dot(csr.T, dns) is slow in nature since every thread has to go through all the rows to find the corresponding column for performing inner product of the column vector of the csr and column vector of the dns. We can do some search online to see if there are better algorithms to adopt.

In addition, the current implementation greatly depends on the layout of non-zero elements of the csr matrix. If most of the rows are non-zero or the elements of a row are scattered throughout the column, it is going to be slow.

**Comment by eric-haibin-lin** [comment]
Thought for improvement:
Let's say the output has 1M rows, and k threads perform dot(csr.T, dns) in parallel. Each thread i is responsible for consecutive rows from `i * 1M / k` to `(i + 1) * 1M / k` of the output matrix. Each thread performs:
```
seg_start = i * 1M / k
seg_end = (i + 1) * 1M / k
for index in csr.indices:
      if index in range [seg_start, seg_end):
          for col in range(dns_num_columns):
              out[index][col] += dns[index, col] * value from csr
```

len(csr.indices) is usually 100 * batch_size so linear scanning indices should not be very expensive, comparing to number of rows in output matrix. Current kernel requires a binary search for each element in the output matrix.

**Comment by reminisce** [comment]
Good thinking, but the last line seems not right.
The row index for dns on the right hand side should be the row index of the "value" in the csr, which requires a binary search throughout csr.indptr for it.

The csr format is nature inefficient in finding a value's row index. To address this issue, this paper might be helpful. But not sure if it's worth the effort of implementing it.
http://people.cs.georgetown.edu/~jfineman/papers/csb.pdf

**Comment by eric-haibin-lin** [comment]
Yeah you're right. Revised with the correct index:
```
seg_start = i * 1M / k
seg_end = (i + 1) * 1M / k
for index in csr.indices:
      if index in range [seg_start, seg_end):
          dns_index = binary_search(indptr)
          for col in range(dns_num_columns):
              out[index][col] += dns[dns_index, col] * value from csr
```
Let's say the shape for output is (m,n).
Time complexity for single thread should be `O(num_thread * nnz * (binary_search + n))`, where binary_search takes `O(logm)`
If done in parallel, time cost should be `O(nnz * (binary_search + n))`

While the current implementation is around `O((m*n) * m * binary_search)` single thread, where binary_search takes O(10), assuming on average 10 nnz per row. 
In parallel time cost is `O((m*n) * m * binary_search / num_thread)`

We should expect good perf improvement for cpu case. We can ponder on gpu performance since it's not high priority. 

If this doesn't work out, next thought would be resort to [MKL](https://software.intel.com/en-us/mkl-developer-reference-c-mkl-csrmm#E03AF2A9-2882-4259-A23A-7C0A1EEB6665).

**Comment by eric-haibin-lin** [comment]
Going for CSB requires lots of work. MKL supports this storage format. I don't think it's going to happen for this version.

**Comment by eric-haibin-lin** [comment]
We should also use openmp reduction to replace std::accumulate
https://software.intel.com/en-us/articles/getting-started-with-openmp

**Comment by reminisce** [comment]
Ok, I will create a PR including these two changes.

**Comment by mli** [comment]
here is a reference implementation, i don't think transpose times will be 10x time slower

https://github.com/dmlc/difacto/blob/master/src/common/spmm.h

**Comment by eric-haibin-lin** [comment]
Closing PR for now and moving discussion to https://github.com/eric-haibin-lin/mxnet/issues/60

**Pull request closed without merging**
